apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: isbim-web
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/managed-by: kubectl
images:
  - name: isbim-official-web
    newName: swr.ap-southeast-1.myhuaweicloud.com/replace-me/isbim-official-web
    newTag: replace-me
